/*
 * Triangular, pentagonal, and hexagonal
 *
 * Problem 45
 *
 * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
 *
 * Triangle                Tn = n(n + 1)/2         1, 3, 6, 10, 15, ...
 * Pentagonal              Pn = n(3n - 1)/2        1, 5, 12, 22, 35, ...
 * Hexagonal               Hn = n(2n - 1)          1, 6, 15, 28, 45, ...
 *
 * It can be verified that T285 = P165 = H143 = 40755.
 *
 * Find the next triangle number that is also pentagonal and hexagonal.
 *
 *
 * problem45.c
 *
 *  Created on: Jan 13, 2014
 *      Author: jcyescas
 */

#include <math.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../lib/util.h"
#include "../lib/list.h"

/* Keeps the result of the quadratic expression.
 *
 * Note: It doesn't keep values for imaginary numbers, only for real numbers.
 */
struct quadratic_result {
  bool imaginary;       // Indicates if it's an imaginary number.
  double x1;
  double x2;
};

/* Returns the result of the quadratic expression. It resolves the equation
 *
 *    ax^2 + bx + c
 *
 * with the formula:
 *
 *    x12 = (-b +/- sqr(b^2 - 4ac))/2a
 *
 * @param a value for the a coefficient.
 * @param b value for the b coefficient.
 * @param c value for the c coefficient.
 * @return the result values for the quadratic expression.
 */
struct quadratic_result quadratic_formula(int64_t a, int64_t b, int64_t c) {
  struct quadratic_result result;
  double first_part = b * b - (4 * a * c);
  if (first_part < 0) {
    result.imaginary = true;
    return result;
  }
  result.imaginary = false;

  first_part = sqrt(first_part);
  result.x1 = ((-1) * b + first_part) / (2 * a);
  result.x2 = ((-1) * b - first_part) / (2 * a);

  return result;
}

void print_quadratic_result(struct quadratic_result * result) {
  if (result->imaginary) {
    printf("\nImaginary");
  } else {
    printf("\nx1 = %f, x2 = %f", result->x1, result->x2);
  }
}

struct quadratic_result triangle(int64_t c) {
  // Triangle           n ^ 2 + n -2Tn = 0
  return quadratic_formula(1, 1, -2 * c);
}

struct quadratic_result pentagonal(int64_t c) {
  // Pentagonal         3n ^ 2 - n - 2Pn = 0
  return quadratic_formula(3, -1, -2 * c);
}

struct quadratic_result hexagonal(int64_t c) {
  // Pentagonal         3n ^ 2 - n - 2Pn = 0
  return quadratic_formula(2, -1, -1 * c);
}

bool has_positive_integer(struct quadratic_result *result) {
  if (result->imaginary)
    return false;

  double x = (int64_t)  result->x1;
  if (result->x1 > 0 && (result->x1 - x) == 0)
    return true;

  x = (int32_t) result->x1;
  if (result->x1 > 0 && (result->x1 - x) ==  0)
    return true;

  return false;
}


int main() {
  printf("\nTriangular, pentagonal, and hexagonal");

  int8_t founds = 0;
  int64_t i;
  for (i = 1; founds < 3; i++) {
    struct quadratic_result r1 = triangle(i);
    struct quadratic_result r2 = pentagonal(i);
    struct quadratic_result r3 = hexagonal(i);

    if (has_positive_integer(&r1) && has_positive_integer(&r2) && has_positive_integer(&r3)) {
      founds++;
      printf("\n\nNumber: %llu", i);
      print_quadratic_result(&r1);
      print_quadratic_result(&r2);
      print_quadratic_result(&r3);
    }
  }
}








