/*
 * Distinct powers
 *
 *
 * Problem 29
 * Consider all integer combinations of a^b for 2 ² a ² 5 and 2 ² b ² 5:
 *
 * 2^2=4, 2^3=8, 2^4=16, 2^5=32
 * 3^2=9, 3^3=27, 3^4=81, 3^5=243
 * 4^2=16, 4^3=64, 4^4=256, 4^5=1024
 * 5^2=25, 5^3=125, 5^4=625, 5^5=3125
 *
 * If they are then placed in numerical order, with any repeats removed, we get the
 * following sequence of 15 distinct terms:
 *
 * 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
 *
 * How many distinct terms are in the sequence generated by a^b for 2 ² a ² 100 and 2 ² b ² 100?
 *
 * problem29.c
 *
 *  Created on: Jan 11, 2014
 *      Author: jcyescas
 */

#include <stdbool.h>
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include "../lib/biginteger.h"
#include "../lib/hash.h"
#include "../lib/list.h"
#include "../lib/util.h"


#define MAX_SIZE 10

/* Gets the number of distinct terms that are in the sequence generated by a^b.
 *
 * @param a is the coeficient
 * @param b is the power
 * @return the number of distinct terms that are in the sequence generated by a^b.
 */
uint32_t get_number_of_distinct_terms(uint32_t a, uint32_t b) {
  struct hash hash_numbers;
  hash_init(&hash_numbers, big_integer_hash, big_integer_compare_asc, NULL);

  int32_t i;
  int32_t j;
  char na[MAX_SIZE];
  char nb[MAX_SIZE];
  for (i = a; i <= b; i++) {
    for (j = a; j <=b; j++) {

      sprintf(na, "%d", i);
      sprintf(nb, "%d", j);
      struct big_integer *bi1 = big_integer_create_from_string(na);
      struct big_integer *bi2 = big_integer_create_from_string(nb);
      struct big_integer *bi_pow = big_integer_pow(bi1, bi2);

      char result[bi_pow->size + 1];
      big_integer_to_string(bi_pow, result);
      printf("(%d ^ %d = %s) ", i, j, result);

      // Inserting the element in the hash table.
      struct hash_elem *inserted = hash_insert(&hash_numbers, &bi_pow->hash_elem);
      if(inserted != NULL) {
        // The element is in the table a it's necessary to destroy it.
        big_integer_destroy(bi_pow);
      }

      // Releasing resources from the big_integer.
      big_integer_destroy(bi1);
      big_integer_destroy(bi2);
    }
    printf("\n");
  }

  // Getting the size of the hash table.
  int32_t size = hash_size(&hash_numbers);

  // Release the resources from the hash table.
  hash_clear(&hash_numbers, big_integer_free_memory_hash);

  return size;
}

int main() {
  printf("Distinct powers\n");

  uint32_t a = 2;
  uint32_t b = 100;
  int32_t size = get_number_of_distinct_terms(a, b);

  printf("The number of distinct terms in the sequence generated by "
      "a^b for %u ² a ² %u and %u ² b ² %u is: %d", a, b, a, b, size);
}

