/*
 *
 * Even Fibonacci numbers
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 *
 * Result: 4613732
 *
 * main.c
 *
 *  Created on: Dec 16, 2013
 *      Author: jcyescas
 */

#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>


/**
 * Returns if the the number is even.
 *
 * @param number to be tested if it's even
 */
bool is_even(uint32_t number) {
  return number % 2 == 0;
}

/* Calculates the sum of the even-values that belongs to the Fibonacci sequence.
 *
 * @param limit is the maximum number that will be used as Fibonnacci number.
 */
uint32_t fibonacci_even_sum(uint32_t limit) {

  uint32_t first = 1;
  uint32_t second = 1;
  uint32_t sum = 0;

  printf("%u, %u", first, second);
  uint32_t tmp;
  for (;first <= limit && second <= limit;) {
      tmp = first;
      first = first + second;
      second = second + first;
      printf(", %u, %u", first, second);

      if (is_even(first) && first <= limit)
        sum += first;

      if (is_even(second) && second <= limit)
        sum += second;
  }

  return sum;
}

int main() {
  printf("Even Fibonacci numbers\n");

  uint32_t limit = 4000000;
  uint32_t result = fibonacci_even_sum(limit);

  printf("\nResult: %u\n", result);

  printf("\nEnd\n");

}
