/*
 * Highly divisible triangular number
 *
 * Problem 12
 *
 * The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 *
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *
 * Let us list the factors of the first seven triangle numbers:
 *
 *  1: 1
 *  3: 1,3
 *  6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 *
 * We can see that 28 is the first triangle number to have over five divisors.
 *
 * What is the value of the first triangle number to have over five hundred divisors?
 *
 * problem12.c
 *
 *  Created on: Dec 26, 2013
 *      Author: jcyescas
 */

#include <math.h>
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include "../lib/util.h"
#include "../lib/list.h"

/* Gets the first triangle number that contains n multiples.
 *
 * @param number_multiples that the triangle number to find at least will have.
 * @return the triangle number that has n multiples.
 */
uint64_t get_first_triangle_number(uint32_t number_multiples) {
  uint64_t triangle_number = 0;

  // What is the maximum number of prime numbers that the first triangle number must have.
  uint32_t number_diff_prime_multiples = round(log2(number_multiples));

  // Subtracting from the prime multiples the 1 and the same number.
  number_diff_prime_multiples = number_diff_prime_multiples > 2 ?
      number_diff_prime_multiples - 2: number_diff_prime_multiples;

  uint64_t i = 1;
  while (true) {
    // Calculating the next triangle number.
    triangle_number = triangle_number + i;
    i++;

    struct list *prime_multiples = get_multiples(triangle_number);

    uint32_t repeat_multiples_size = list_size(prime_multiples);

    // Removing duplicates from the list.
    list_unique(prime_multiples, NULL, compare_long_number_asc, NULL);

    uint32_t primes_size = list_size(prime_multiples);

    if (primes_size >= number_diff_prime_multiples) {
      // Size of the compound multiples (Compound multiples because they are formed by primes.)
      struct list *list_dist_multiples = get_distinct_multiples(triangle_number);
      uint32_t compound_multiples_size = list_size(list_dist_multiples);

      free_memory_long_number_list(list_dist_multiples);
      free(list_dist_multiples);

      if (compound_multiples_size >= number_multiples) {
        struct long_number *ln;
        struct list_elem *temp;
        printf("\nTriangle number and number of all multiples: [%u, %u]\n",
            triangle_number, compound_multiples_size);
        printf("Prime multiples { ");
        for (temp = list_begin(prime_multiples); temp != list_end(prime_multiples);
            temp = list_next(temp)) {
          ln = list_entry(temp, struct long_number, elem);
          printf("%llu ", ln->number);
        }
        printf("}");
        printf("\nTotal prime numbers including repeated: %u", repeat_multiples_size);

        free_memory_long_number_list(prime_multiples);
        free(prime_multiples);

        break;
      }
    }

    free_memory_long_number_list(prime_multiples);
    free(prime_multiples);
  }

  return triangle_number;
}


int main() {
  printf("Highly divisible triangular number\n");

  uint32_t multiples = 6;
  uint64_t triangle_number = get_first_triangle_number(multiples);

  printf("\nTriangle number with more than %u or equal to %u multiples is: %llu\n",
      multiples, multiples, triangle_number);

  multiples = 500;
  triangle_number = get_first_triangle_number(multiples);
  printf("\nTriangle number with more than %u or equal to %u multiples is: %llu",
      multiples, multiples, triangle_number);

  return 0;
}

